from typing import Optional
from pydantic import BaseModel, Field

class InvoiceData(BaseModel):
    vendor_name: str = Field(..., description="Name of the vendor/company issuing the invoice.")
    purchase_category: str = Field(..., description="Category of the purchased products or services in German (e.g. 'Büromaterial', 'Geschäftsessen', 'Telekommunikation', 'Fahrtkosten', ...)")
    invoice_number: str = Field(..., description="The unique identifier/number of the invoice.")
    date: str = Field(..., description="The date of the invoice in ISO 8601 format (YYYY-MM-DD).")
    total_invoice_amount_gross: float = Field(..., description="The total gross amount of the invoice.")
    total_invoice_amount_net: float = Field(..., description="The total net amount of the invoice.")
    total_invoice_amount_tax: float = Field(..., description="The total tax amount of the invoice.")
    tip_amount: float = Field(0.0, description="The tip amount, if specified on the invoice or receipt.")
    total_payment_amount_gross: Optional[float] = Field(None, description="The total payment amount, if a payment receipt is present. May include tips.")
    tax_amount_0_percent_VAT: float = Field(0.0, description="Tax amount for 0% VAT.")
    tax_amount_10_percent_VAT: float = Field(0.0, description="Tax amount for 10% VAT.")
    tax_amount_13_percent_VAT: float = Field(0.0, description="Tax amount for 13% VAT.")
    tax_amount_20_percent_VAT: float = Field(0.0, description="Tax amount for 20% VAT.")
    net_amount_0_percent_VAT: float = Field(0.0, description="Net amount that is to be taxed with 0% VAT.")
    net_amount_10_percent_VAT: float = Field(0.0, description="Net amount that is to be taxed with 10% VAT.")
    net_amount_13_percent_VAT: float = Field(0.0, description="Net amount that is to be taxed with 13% VAT.")
    net_amount_20_percent_VAT: float = Field(0.0, description="Net amount that is to be taxed with 20% VAT.")
    currency: str = Field("EUR", description="3-letter currency code (e.g., EUR, USD).")
    iban: Optional[str] = Field(None, description="The IBAN of the vendor for payment.")
    payment_method: Optional[str] = Field(None, description="The payment method used for the transaction (e.g. 'Bankkonto', 'bar', ...).")
    gdrive_link: Optional[str] = Field(None, description="A Google Drive link to the original scan document.")
